name: twist_music_player_example
description: Demo host for twist_music_player.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  iconsax: ^0.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  twist_music_player:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
